# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radiowindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Radiochoice(object):
    def setupUi(self, Radiochoice):
        Radiochoice.setObjectName("Radiochoice")
        Radiochoice.resize(365, 140)
        self.verticalLayout = QtWidgets.QVBoxLayout(Radiochoice)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(Radiochoice)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.line = QtWidgets.QFrame(Radiochoice)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.pushButton = QtWidgets.QPushButton(Radiochoice)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Radiochoice)
        QtCore.QMetaObject.connectSlotsByName(Radiochoice)

    def retranslateUi(self, Radiochoice):
        _translate = QtCore.QCoreApplication.translate
        Radiochoice.setWindowTitle(_translate("Radiochoice", "Выбор радиостанции"))
        self.comboBox.setItemText(0, _translate("Radiochoice", "Рок"))
        self.comboBox.setItemText(1, _translate("Radiochoice", "Поп"))
        self.comboBox.setItemText(2, _translate("Radiochoice", "Рэп"))
        self.comboBox.setItemText(3, _translate("Radiochoice", "Танцевальная"))
        self.comboBox.setItemText(4, _translate("Radiochoice", "Техно"))
        self.comboBox.setItemText(5, _translate("Radiochoice", "Джаз"))
        self.comboBox.setItemText(6, _translate("Radiochoice", "Юмор"))
        self.pushButton.setText(_translate("Radiochoice", "ОК"))
